"""auto add columns

Revision ID: c96c3feafed7
Revises: 0002_drop_bank_transactions
Create Date: 2026-03-20 17:06:58.912901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003_auto_add_columns'
down_revision: Union[str, None] = '0002_drop_bank_transactions'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    if conn.dialect.name == "postgresql":
        op.execute("ALTER TABLE invoices ADD COLUMN IF NOT EXISTS payment_code TEXT DEFAULT ''")
    else:
        # SQLite doesn't natively support ADD COLUMN IF NOT EXISTS cleanly in all versions.
        # we will use try/except block just in case
        try:
            op.add_column('invoices', sa.Column('payment_code', sa.Text(), server_default=''))
        except Exception:
            pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'payment_code')
    # ### end Alembic commands ###
