"""Add notifications_enabled to SupplierProfile

Revision ID: e1f0b00bb6d8
Revises: 0004_postgres_safety
Create Date: 2026-03-22 19:51:00.997080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1f0b00bb6d8'
down_revision: Union[str, None] = '0004_postgres_safety'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplier_profile', sa.Column('notifications_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supplier_profile', 'notifications_enabled')
    # ### end Alembic commands ###
